#!/usr/bin/env python3
"""
Generate the synthetic proxy corpus used by this artifact's claims.

The paper's experiments used a malware corpus that cannot be redistributed.
Following the ACSAC call's provision for proprietary data, this script builds a
stand-in corpus that exercises the full AutoPYara pipeline without shipping any
malicious code.

WHAT IT PRODUCES

    Pseudo-random binary files, arranged in `--families` groups. Every file in
    a group shares a set of planted byte sequences that appear nowhere else, so
    the n-gram extraction and clustering stages have real structure to find,
    the way they would with a genuine malware family.

    The output contains no malicious code, no real-world binaries, and no
    third-party data. It is generated from a fixed seed, so the corpus is
    identical on every run and on every machine.

WHY PLANTED PATTERNS ARE NEEDED

    AutoPYara looks for byte n-grams that are common across the input samples
    but rare in its benign/malicious Bloom filters. Purely random files share
    no n-grams at all beyond chance, so the pipeline would run but find nothing
    worth emitting. The planted sequences give it something to legitimately
    discover.

USAGE

    python3 make_proxy_corpus.py --out /tmp/proxy_corpus
    python3 make_proxy_corpus.py --out /tmp/corpus --families 3 --per-family 4
"""
import argparse
import os
import random
import shutil
import sys

# Fixed so the corpus is byte-identical everywhere. Nothing here depends on
# system entropy.
SEED = 20260909

# Planted sequences are this long. 16 bytes comfortably exceeds the largest
# n-gram size AutoPYara extracts (1024 bits = 128 bytes at the top end, but the
# useful signal sits in the 8-64 byte range), so a planted run of this size
# survives into the candidate set.
PATTERN_LEN = 64
PATTERNS_PER_FAMILY = 6


def build_corpus(out_dir, families, per_family, size_kb):
    rng = random.Random(SEED)

    if os.path.exists(out_dir):
        shutil.rmtree(out_dir)
    os.makedirs(out_dir)

    size = size_kb * 1024
    manifest = []

    for fam in range(families):
        # Sequences shared by every member of this family and no other.
        patterns = [
            bytes(rng.getrandbits(8) for _ in range(PATTERN_LEN))
            for _ in range(PATTERNS_PER_FAMILY)
        ]

        for member in range(per_family):
            data = bytearray(rng.getrandbits(8) for _ in range(size))

            # Splice the family's patterns in at spread-out offsets so they are
            # not adjacent and not at a constant position across files.
            for i, pat in enumerate(patterns):
                span = size // PATTERNS_PER_FAMILY
                base = i * span
                jitter = rng.randrange(0, max(1, span - PATTERN_LEN))
                at = min(base + jitter, size - PATTERN_LEN)
                data[at:at + PATTERN_LEN] = pat

            name = f"family{fam:02d}_sample{member:02d}.bin"
            path = os.path.join(out_dir, name)
            with open(path, "wb") as fh:
                fh.write(bytes(data))
            manifest.append((name, fam))

    with open(os.path.join(out_dir, "MANIFEST.txt"), "w") as fh:
        fh.write("Synthetic proxy corpus for the AutoPYara ACSAC artifact.\n")
        fh.write("Generated by make_proxy_corpus.py -- contains NO malicious code.\n\n")
        fh.write(f"seed={SEED} families={families} per_family={per_family} "
                 f"size={size_kb}KB pattern_len={PATTERN_LEN} "
                 f"patterns_per_family={PATTERNS_PER_FAMILY}\n\n")
        fh.write("file,ground_truth_family\n")
        for name, fam in manifest:
            fh.write(f"{name},{fam}\n")

    return [os.path.join(out_dir, n) for n, _ in manifest]


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", required=True, help="output directory (recreated if present)")
    ap.add_argument("--families", type=int, default=2, help="number of synthetic families")
    ap.add_argument("--per-family", type=int, default=3, help="samples per family")
    ap.add_argument("--size-kb", type=int, default=48, help="size of each sample, in KB")
    args = ap.parse_args()

    if args.families < 1 or args.per_family < 1:
        print("error: --families and --per-family must be >= 1", file=sys.stderr)
        return 1

    files = build_corpus(args.out, args.families, args.per_family, args.size_kb)

    total = args.families * args.per_family
    print(f"Wrote {total} synthetic samples "
          f"({args.families} families x {args.per_family}) to {args.out}")
    print(f"Each sample is {args.size_kb} KB of pseudo-random data containing "
          f"{PATTERNS_PER_FAMILY} planted {PATTERN_LEN}-byte family patterns.")
    print("Ground truth is recorded in MANIFEST.txt. No malicious code is present.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
